### PR TITLE
Builtin oracle improvements

### LINKED ISSUE #7: Make a builtin oracle handler
**What is the Problem Being Solved?**
People testing the Chainlink integration would like to test their contracts before instantiating them on a public network that has genuine Chainlink oracle nodes, nor having to spin up their own Chainlink node.

**Description of the Design**
Have the default execution of `dapp-oracle/api/deploy.js` create an oracle contract instance with a simple builtin  oracle handler using a tiny subset of the Chainlink Any API:

```js
E(testOraclePublicFacet).query({ jobId: '<chainlink-jobid>', params:{ 
  get: "https://bitstamp.net/api/ticker/",
  path: ["last"],
  times: 100
 }
}).then(reply => reply === '1309766')
```

This `'<chainlink-jobid>'` jobId would be the same as the Chainlink sample job:
```json
{
  "initiators": [
    {
      "type": "external",
      "params": {
        "name": "test-ei",
        "body": {
          "endpoint": "agoric-node"
        }
      }
    }
  ],
  "tasks": [
    {
      "type": "HTTPGet"
    },
    {
      "type": "JSONParse"
    },
    {
      "type": "Multiply"
    },
    {
      "type": "Agoric"
    }
  ]
}
```

Specifically, this query will accept a `get` parameter of a URL to download, a `path` parameter telling it to `JSON.parse` the retrieved data and narrow to a sub-property of the `data` and then finally multiply it by the `times` parameter.

Such a handler needs to use the `local.plugin` mechanism to enable access to an actual HTTP client Javascript API.

**Security Considerations**
Exposing this oracle to other entities may enable access to resources that only the ag-solo's owner should be able to reach.  For that reason, it should not be passed to untrusted objects.

**Test Plan**

The above.

### PR DESCRIPTION
**Pull request by michaelfig**
Properly implement the Chainlink Adapter APIs for HttpGet, HttpPost, JsonParse, and Multiply.

Closes #7

### CODE REVIEW

**Review by Chris-Hibbert — COMMENTED** [review]
The parts of this that I understand look fine. I didn't follow all the http wiring (which is most of it.) 

How has this been tested?

**Comment by michaelfig** [comment]
> How has this been tested?

Mostly manually, but it would be useful to write some unit tests.  First I want to work on Agoric/agoric-sdk#1944.

**Comment by Chris-Hibbert** [comment]
> Mostly manually, but it would be useful to write some unit tests. 

Not quite the level of detail I was looking for. I presumed "manually", and was wondering how thoroughly you feel you've exercised it. I understand useful unit tests of this kind of functionality can be hard to design, and I'm okay without it as long as most of the functionality has been tried. If I had (or another reviewer does) understood it better, I might not ask, but the details elude me.

**Comment by michaelfig** [comment]
> > Mostly manually, but it would be useful to write some unit tests.

> Not quite the level of detail I was looking for. I presumed "manually", and was wondering how thoroughly you feel you've exercised it.

I've tested it with gets and posts to both public (allowed) and private (denied) web sites, and gotten both raw results, JSON-processed, and multiplied by a factor of 10.  Things work and fail as expected.

> I understand useful unit tests of this kind of functionality can be hard to design, and I'm okay without it as long as most of the functionality has been tried.

Okay.

> If I had (or another reviewer does) understood it better, I might not ask, but the details elude me.

The API description is mostly in the README, with links to the Chainlink docs describing the adapters that are pipelined over the oracle query parameters.  It's a lot to take in, so I'm not expecting full understanding.

**Review by katelynsills — APPROVED** [review]
This looks ok to me, but I want to make sure that documentation on the documentation site and tests for this don't get lost. Can we make issues for both of those and assign people to it? I would be happy to add something like puppeteer to this if we want to test the frontend response.

**Comment by michaelfig** [comment]
> This looks ok to me, but I want to make sure that documentation on the documentation site and tests for this don't get lost. Can we make issues for both of those and assign people to it?

I've done this: #9 and #10

> I would be happy to add something like puppeteer to this if we want to test the frontend response.

That may be further off... it would require creating a backend with a fakeable oracle handler.  We can at least target unit tests to cover the bulk of the work before that.

**Pull request merged**
